### ISSUE TITLE
Error when running the site locally

### ISSUE THREAD

**Issue by najela** [gdg-x/zeppelin#76]
When I run `jekyll serve -w` I get the error

```bash
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.3)
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/najela/OpenSource/GitHub/myGithub/devfest-mezam/_config.yml
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

This is my output for `bundle install`

```bash
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using addressable 2.3.8
Using execjs 2.6.0
Using autoprefixer-rails 6.0.2
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.4
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1.1
Using coffee-script 2.4.1
Using colorator 0.1
Using multi_json 1.11.2
Using sass 3.4.18
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.6
Using ffi 1.9.10
Using rb-inotify 0.9.5
Using compass 1.0.3
Using ethon 0.7.4
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.1
Using typhoeus 0.7.3
Using github-pages-health-check 0.5.3
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.3.4
Using jekyll-paginate 1.1.0
Using jekyll-sass-converter 1.3.0
Using listen 2.10.1
Using jekyll-watch 1.2.1
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.5
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using pygments.rb 0.6.3
Using redcarpet 3.3.2
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.4.0
Using jekyll-feed 0.3.1
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using html-pipeline 1.9.0
Using jekyll-mentions 0.2.1
Using jekyll-redirect-from 0.8.0
Using jekyll-sitemap 0.8.1
Using jemoji 0.5.0
Using maruku 0.7.0
Using rdiscount 2.1.7
Using terminal-table 1.5.2
Using github-pages 39
Using sass-media_query_combiner 0.0.7
Using bundler 1.10.5
Bundle complete! 4 Gemfile dependencies, 65 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by ozasadnyy** [comment]
Strange, it seems like `jekyll-sitemap` is missed however it should be included into `github-pages` gem.
Try to run `gem 'jekyll-sitemap'` and let me know about your results

**Comment by Ch3ck** [comment]
which repo is this? I thought you were using my fork gdgbambili repo?

**Comment by ozasadnyy** [comment]
@Ch3ck it gdg[x] repo.

**Comment by najela** [comment]
@ozasadnyy  I've solved the issue. I had to run jekyll with `bundle exec jekyll serve`
